version: '3.8'

services:
  mysqldbservice:
    build: ./mysql
    container_name: mysqldb_service
    environment:
      MYSQL_ROOT_PASSWORD: Admin@123
      MYSQL_DATABASE: mydb
      MYSQL_USER: admin
      MYSQL_PASSWORD: Admin@123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  mongodbservice:
    build: ./mongo
    container_name: mongodb_service
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  authenticationservice:
    build: ./AuthenticationService
    image: authenticationservice:latest
    container_name: authentication_service
    ports:
      - "8082:8080"
    depends_on:
      - mysqldbservice
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldbservice:3306/mydb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: Admin@123
    networks:
      - app-network

  dataentry:
    build: ./DataEntryService
    image: dataentryservice:latest
    container_name: data_entry_service
    ports:
      - "8080:8080"
    depends_on:
      - authenticationservice
      - mysqldbservice
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldbservice:3306/mydb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: Admin@123
    networks:
      - app-network

  showresults:
    build: ./ShowResultsService
    image: showresultsservice:latest
    container_name: show_results_service
    ports:
      - "8081:8080"
    depends_on:
      - authenticationservice
      - mongodbservice
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodbservice:27017/Resultdb
    networks:
      - app-network

  analyticsservice:
    build: ./AnalyticsService
    image: analyticsservice:latest
    container_name: analytics_service
    ports:
      - "8083:8080"
    depends_on:
      - mysqldbservice
      - mongodbservice
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldbservice:3306/mydb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: Admin@123
      SPRING_DATA_MONGODB_URI: mongodb://mongodbservice:27017/Resultdb
    networks:
      - app-network

volumes:
  mysql_data:
  mongo_data:

networks:
  app-network:
    driver: bridge
